wandb:
  project: "len_gen_pretrained"
  entity: "lacoco-lab"  # replace with your Wandb username or organization

model:
  vocab_size: 6
  n_positions: 512
  n_ctx: 512
  n_embd: 32
  n_layer: 2
  n_head: 4
  pad_token_id: 5

dataset:
  train:
    name: "first"
    min_len: 50
    max_len: 200
    total_samples: 10000
  val:
    name: "first"
    min_len: 200
    max_len: 500
    total_samples: 10000

train:
  output_dir: "results"
  num_train_epochs: 100
  per_device_train_batch_size: 32
  evaluation_strategy: "steps"
  eval_steps: 50
  logging_steps: 10
  save_steps: 100
