
wandb:
  use_wandb: True
  project: "len_gen_pretrained"
  entity: "lacoco-lab"  # replace with your Wandb username or organization

model:
  vocab_size: 6
  n_positions: 512
  n_ctx: 512
  n_embd: 64
  n_layer: 4
  n_head: 4
  pad_token_id: 5

dataset:
  train:
    name: "first"
    min_len: 50
    max_len: 300
    total_samples: 10000
    output_dir: "models"
  val:
    name: "first"
    min_len: 300
    max_len: 500
    total_samples: 4000

train:
  output_dir: "results"
  num_train_epochs: 500
  per_device_train_batch_size: 32
  evaluation_strategy: "steps"
  eval_steps: 200
  logging_steps: 50
  save_steps: 2000